---
- name: pip modules to secure access to Ansible Galaxy
  pip:
    name: awscli
    executable: "{{ '/opt/pyenv/shims/pip' if ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' else omit }}"
  when: ansible_distribution != 'Amazon' or 'container' in group_names

- name: create AWS config directory
  file:
    path: ~/.aws
    state: directory
    owner: root
    group: root
    mode: 0700

- name: set AWS credentials file
  template:
    src: credentials.j2
    dest: ~/.aws/credentials
    owner: root
    group: root
    mode: 0600
