---
- name: pip modules to secure access to Ansible Galaxy
  pip:
    name: awscli
    executable: "{{ '/opt/pyenv/shims/pip' if ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' else omit }}"
  when: ansible_distribution != 'Amazon' or 'container' in group_names

- name: create AWS config directory
  file:
    path: ~/.aws
    state: directory
    owner: root
    group: root
    mode: 0700

- name: set AWS credentials file
  template:
    src: credentials.j2
    dest: ~/.aws/credentials
    owner: root
    group: root
    mode: 0600

- name: change timezone as JST
  copy:
    src: /usr/share/zoneinfo/Japan
    dest: /etc/localtime
    remote_src: yes

- name: check whether /etc/sysconfig/clock exist or not
  stat:
    path: /etc/sysconfig/clock
  register: stat_sysconfig_clock

- name: set timezone as JST
  replace:
    path: /etc/sysconfig/clock
    regexp: ^ZONE\s*=\s*"UTC"
    replace: ZONE="Asia/Tokyo"
  when: stat_sysconfig_clock.stat.exists

- name: set timezone as JST
  template:
    src: clock.j2
    dest: /etc/sysconfig/clock
    owner: root
    group: root
    mode: 0644
  when: not stat_sysconfig_clock.stat.exists

- name: install yum-plugin-fastestmirror
  yum:
    name: yum-plugin-fastestmirror
